# Generated by Django 4.2.11 on 2024-04-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="subTask1",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask10",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask11",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask12",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask13",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask14",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask15",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask16",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask17",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask18",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask19",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask2",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask20",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask3",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask4",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask5",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask6",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask7",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask8",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTask9",
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted1",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted10",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted11",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted12",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted13",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted14",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted15",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted16",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted17",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted18",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted19",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted2",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted20",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted3",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted4",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted5",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted6",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted7",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted8",
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="subTaskCompleted9",
            field=models.BooleanField(default=None),
        ),
    ]
