# Generated by Django 5.0.3 on 2024-04-15 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UserFarm',
        ),
        migrations.RenameModel(
            old_name='UserCrop',
            new_name='UserSeeds',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='autoHideTime',
        ),
        migrations.AddField(
            model_name='tasks',
            name='breakTime',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7200)]),
        ),
    ]
