# Generated by Django 5.0.3 on 2024-04-16 03:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFarm',
            fields=[
                ('usernameId', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('farmHouseLevel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)])),
                ('x', models.PositiveIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(640)])),
                ('y', models.PositiveIntegerField(default=570, validators=[django.core.validators.MaxValueValidator(1200)])),
                ('email', models.EmailField(default='blank', max_length=254)),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='usernameId',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='userplots',
            name='usernameId',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='userdecorations',
            name='usernameId',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='userfurniture',
            name='usernameId',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='userdates',
            name='usernameId',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='inBreak',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='autoHideTime',
        ),
        migrations.AddField(
            model_name='tasks',
            name='timerState',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddField(
            model_name='tasks',
            name='timerTime',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7200)]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='fontStyle',
            field=models.CharField(default='pixelArt', max_length=15),
        ),
        migrations.CreateModel(
            name='UserSeeds',
            fields=[
                ('usernameId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PVdb.userfarm')),
                ('tomato', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('sunflower', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('carrot', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('pumpkin', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('tulip', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='usernameId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PVdb.userfarm'),
        ),
        migrations.DeleteModel(
            name='UserCrop',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
