# Generated by Django 5.0.3 on 2024-04-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0002_rename_users_userfarm_rename_usercrop_userseeds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseeds',
            name='usernameId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PVdb.userfarm'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='usernameId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PVdb.userfarm'),
        ),
    ]
