# Generated by Django 4.2.11 on 2024-04-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0003_remove_tasks_subtask11_remove_tasks_subtask12_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="subTask1",
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask10",
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask2",
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask3",
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask4",
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask5",
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask6",
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask7",
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask8",
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask9",
            field=models.CharField(default=None, max_length=32),
        ),
    ]
