# Generated by Django 4.2.11 on 2024-04-12 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0005_rename_taskcompleted_tasks_completed_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="username",
            new_name="usernameId",
        ),
        migrations.RenameField(
            model_name="usercrop",
            old_name="username",
            new_name="usernameId",
        ),
        migrations.RenameField(
            model_name="userdates",
            old_name="username",
            new_name="usernameId",
        ),
        migrations.RenameField(
            model_name="userdecorations",
            old_name="username",
            new_name="usernameId",
        ),
        migrations.RenameField(
            model_name="userfurniture",
            old_name="username",
            new_name="usernameId",
        ),
        migrations.RenameField(
            model_name="userplots",
            old_name="username",
            new_name="usernameId",
        ),
        migrations.RenameField(
            model_name="usersettings",
            old_name="username",
            new_name="usernameId",
        ),
        migrations.AlterUniqueTogether(
            name="tasks",
            unique_together={("taskName", "usernameId")},
        ),
        migrations.AlterUniqueTogether(
            name="userdates",
            unique_together={("usernameId", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="userdecorations",
            unique_together={("usernameId", "type")},
        ),
        migrations.AlterUniqueTogether(
            name="userfurniture",
            unique_together={("usernameId", "type")},
        ),
    ]
