# Generated by Django 5.0.3 on 2024-04-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0005_tasks_completiondate_pomodorosession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='completionDate',
        ),
        migrations.DeleteModel(
            name='PomodoroSession',
        ),
    ]
