# Generated by Django 5.0.3 on 2024-04-15 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0008_alter_userseeds_usernameid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfarm',
            name='farmHouseLevel',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userfarm',
            name='x',
            field=models.PositiveIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(640)]),
        ),
        migrations.AlterField(
            model_name='userfarm',
            name='y',
            field=models.PositiveIntegerField(default=570, validators=[django.core.validators.MaxValueValidator(1200)]),
        ),
    ]
