# Generated by Django 4.2.11 on 2024-04-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0008_alter_tasks_subtask1_alter_tasks_subtask10_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tasks",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tasks",
            name="plotId",
            field=models.PositiveIntegerField(
                default=0, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="taskName",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name="tasks",
            unique_together={("plotId", "usernameId")},
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="plotNumber",
        ),
    ]
