# Generated by Django 5.0.3 on 2024-04-15 23:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0009_alter_userfarm_farmhouselevel_alter_userfarm_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfarm',
            name='farmHouseLevel',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userfarm',
            name='x',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(640)]),
        ),
        migrations.AlterField(
            model_name='userfarm',
            name='y',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1200)]),
        ),
        migrations.AlterField(
            model_name='userseeds',
            name='usernameId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PVdb.userfarm'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='fontSize',
            field=models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='fontStyle',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='usernameId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PVdb.userfarm'),
        ),
    ]
