# Generated by Django 5.0.3 on 2024-04-15 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0007_userdates_timespent'),
        ('PVdb', '0009_alter_tasks_unique_together_tasks_plotid_and_more'),
    ]

    operations = [
    ]
