# Generated by Django 5.0.3 on 2024-04-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0013_alter_userfarm_farmhouselevel_alter_userfarm_x_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='usernameId',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='userdates',
            name='usernameId',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='userdecorations',
            name='usernameId',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='userfurniture',
            name='usernameId',
            field=models.CharField(default=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='userplots',
            name='usernameId',
            field=models.CharField(default=False, max_length=150),
        ),
    ]
