# Generated by Django 5.0.3 on 2024-04-16 10:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('worth', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Decorations',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserFarm',
            fields=[
                ('usernameId', models.CharField(max_length=150, primary_key=True, serialize=False, unique=True)),
                ('coins', models.PositiveIntegerField(default=0)),
                ('farmHouseLevel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10)])),
                ('x', models.PositiveIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(640)])),
                ('y', models.PositiveIntegerField(default=570, validators=[django.core.validators.MaxValueValidator(1200)])),
                ('email', models.EmailField(default='blank', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('usernameId', models.CharField(default='false', max_length=150)),
                ('completed', models.BooleanField(default=False)),
                ('plotId', models.PositiveIntegerField(default=0)),
                ('pomodoros', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('pomodorosCompleted', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(20)])),
                ('timerState', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)])),
                ('timerTime', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7200)])),
                ('elapsedTime', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(40)])),
                ('subTask1', models.CharField(default=None, max_length=32, null=True)),
                ('subTaskCompleted1', models.BooleanField(default=None, null=True)),
                ('subTask2', models.CharField(default=None, max_length=32, null=True)),
                ('subTaskCompleted2', models.BooleanField(default=None, null=True)),
                ('subTask3', models.CharField(default=None, max_length=32, null=True)),
                ('subTaskCompleted3', models.BooleanField(default=None, null=True)),
                ('subTask4', models.CharField(default=None, max_length=32, null=True)),
                ('subTaskCompleted4', models.BooleanField(default=None, null=True)),
                ('subTask5', models.CharField(default=None, max_length=32, null=True)),
                ('subTaskCompleted5', models.BooleanField(default=None, null=True)),
                ('subTask6', models.CharField(default=None, max_length=32, null=True)),
                ('subTaskCompleted6', models.BooleanField(default=None, null=True)),
                ('subTask7', models.CharField(default=None, max_length=32, null=True)),
                ('subTaskCompleted7', models.BooleanField(default=None, null=True)),
                ('subTask8', models.CharField(default=None, max_length=32, null=True)),
                ('subTaskCompleted8', models.BooleanField(default=None, null=True)),
                ('subTask9', models.CharField(default=None, max_length=32, null=True)),
                ('subTaskCompleted9', models.BooleanField(default=None, null=True)),
                ('subTask10', models.CharField(default=None, max_length=32, null=True)),
                ('subTaskCompleted10', models.BooleanField(default=None, null=True)),
            ],
            options={
                'unique_together': {('plotId', 'usernameId')},
            },
        ),
        migrations.CreateModel(
            name='UserDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameId', models.CharField(default=False, max_length=150)),
                ('date', models.DateField(default=False)),
                ('timeSpent', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('usernameId', 'date')},
            },
        ),
        migrations.CreateModel(
            name='UserDecorations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameId', models.CharField(default=False, max_length=150)),
                ('type', models.CharField(max_length=30)),
                ('x', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(640)])),
                ('y', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(1200)])),
                ('placed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('usernameId', 'type')},
            },
        ),
        migrations.CreateModel(
            name='UserSeeds',
            fields=[
                ('usernameId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PVdb.userfarm')),
                ('tomato', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('sunflower', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('carrot', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('pumpkin', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('tulip', models.IntegerField(default=-1, validators=[django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('usernameId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PVdb.userfarm')),
                ('pomTimer', models.IntegerField(default=25, validators=[django.core.validators.MaxValueValidator(120)])),
                ('shortBreak', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(120)])),
                ('longBreak', models.IntegerField(default=20, validators=[django.core.validators.MaxValueValidator(120)])),
                ('longBreakInterval', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(20)])),
                ('autoStartPom', models.BooleanField(default=False)),
                ('autoStartBreak', models.BooleanField(default=False)),
                ('fontStyle', models.CharField(default='pixel', max_length=15)),
                ('fontSize', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(15)])),
            ],
        ),
        migrations.CreateModel(
            name='UserFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameId', models.CharField(default=False, max_length=150)),
                ('type', models.CharField(max_length=30)),
                ('x', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(640)])),
                ('y', models.PositiveIntegerField(default=None, validators=[django.core.validators.MaxValueValidator(1200)])),
                ('placed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('usernameId', 'type')},
            },
        ),
        migrations.CreateModel(
            name='UserPlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usernameId', models.CharField(default='guest', max_length=150)),
                ('plotId', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(7)])),
                ('crop', models.CharField(default='nothing', max_length=12)),
                ('growthStage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)])),
                ('growthStep', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(36)])),
                ('x', models.PositiveIntegerField(default=-1000, validators=[django.core.validators.MaxValueValidator(640)])),
                ('y', models.PositiveIntegerField(default=-1000, validators=[django.core.validators.MaxValueValidator(1200)])),
                ('placed', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('plotId', 'usernameId')},
            },
        ),
    ]
