# Generated by Django 4.2.11 on 2024-04-11 15:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Users",
            fields=[
                (
                    "username",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("money", models.PositiveIntegerField(default=0)),
                (
                    "houseStatus",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "housex",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(640)],
                    ),
                ),
                (
                    "housey",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(1200)],
                    ),
                ),
                ("plots", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserCrop",
            fields=[
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="PVdb.users",
                    ),
                ),
                (
                    "tomato",
                    models.IntegerField(
                        default=-1,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "sunflower",
                    models.IntegerField(
                        default=-1,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "carrot",
                    models.IntegerField(
                        default=-1,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "pumpkin",
                    models.IntegerField(
                        default=-1,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                (
                    "tulip",
                    models.IntegerField(
                        default=-1,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="PVdb.users",
                    ),
                ),
                (
                    "pomTimer",
                    models.IntegerField(
                        default=25,
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
                (
                    "shortBreak",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
                (
                    "longBreak",
                    models.IntegerField(
                        default=20,
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
                (
                    "longBreakInterval",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                ("autoStartPom", models.BooleanField(default=False)),
                ("autoStartBreak", models.BooleanField(default=False)),
                ("autoHideTime", models.BooleanField(default=False)),
                ("fontStyle", models.CharField(max_length=15)),
                (
                    "fontSize",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(15)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserPlots",
            fields=[
                (
                    "plotNumber",
                    models.PositiveIntegerField(
                        default=0,
                        primary_key=True,
                        serialize=False,
                        validators=[django.core.validators.MaxValueValidator(7)],
                    ),
                ),
                ("cropType", models.CharField(default=None, max_length=12)),
                (
                    "growthStage",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(10)],
                    ),
                ),
                (
                    "growthStep",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(36)],
                    ),
                ),
                (
                    "x",
                    models.PositiveIntegerField(
                        default=None,
                        validators=[django.core.validators.MaxValueValidator(640)],
                    ),
                ),
                (
                    "y",
                    models.PositiveIntegerField(
                        default=None,
                        validators=[django.core.validators.MaxValueValidator(1200)],
                    ),
                ),
                ("placed", models.BooleanField(default=False)),
                (
                    "username",
                    models.ForeignKey(
                        default=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PVdb.users",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFurniture",
            fields=[
                (
                    "furniture",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "x",
                    models.PositiveIntegerField(
                        default=None,
                        validators=[django.core.validators.MaxValueValidator(640)],
                    ),
                ),
                (
                    "y",
                    models.PositiveIntegerField(
                        default=None,
                        validators=[django.core.validators.MaxValueValidator(1200)],
                    ),
                ),
                ("placed", models.BooleanField(default=False)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="PVdb.users"
                    ),
                ),
            ],
            options={
                "unique_together": {("username", "furniture")},
            },
        ),
        migrations.CreateModel(
            name="UserDecorations",
            fields=[
                (
                    "decoration",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "x",
                    models.PositiveIntegerField(
                        default=None,
                        validators=[django.core.validators.MaxValueValidator(640)],
                    ),
                ),
                (
                    "y",
                    models.PositiveIntegerField(
                        default=None,
                        validators=[django.core.validators.MaxValueValidator(1200)],
                    ),
                ),
                ("placed", models.BooleanField(default=False)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="PVdb.users"
                    ),
                ),
            ],
            options={
                "unique_together": {("username", "decoration")},
            },
        ),
        migrations.CreateModel(
            name="UserDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=False)),
                ("timeSpent", models.PositiveIntegerField(default=0)),
                (
                    "username",
                    models.ForeignKey(
                        default=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PVdb.users",
                    ),
                ),
            ],
            options={
                "unique_together": {("username", "date")},
            },
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "taskName",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("taskCompleted", models.BooleanField(default=False)),
                ("plotNumber", models.PositiveIntegerField(default=0)),
                (
                    "pomodorros",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                (
                    "pomodorrosCompleted",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        default=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PVdb.users",
                    ),
                ),
            ],
            options={
                "unique_together": {("taskName", "username")},
            },
        ),
    ]
