# Generated by Django 5.0.3 on 2024-04-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='fontStyle',
            field=models.CharField(default='pixel', max_length=15),
        ),
    ]
