# Generated by Django 4.2.11 on 2024-04-10 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="taskStatus",
        ),
        migrations.AddField(
            model_name="tasks",
            name="pomodorrosCompleted",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MaxValueValidator(20)]
            ),
        ),
    ]
