# Generated by Django 4.2.9 on 2024-03-04 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usercrop",
            old_name="user",
            new_name="username",
        ),
        migrations.RenameField(
            model_name="userdecorations",
            old_name="user",
            new_name="username",
        ),
        migrations.AlterUniqueTogether(
            name="usercrop",
            unique_together={("username", "crop")},
        ),
        migrations.AlterUniqueTogether(
            name="userdecorations",
            unique_together={("username", "decoration")},
        ),
    ]
