# Generated by Django 4.2.11 on 2024-04-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0002_tasks_subtask1_tasks_subtask10_tasks_subtask11_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tasks",
            name="subTask11",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTask12",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTask13",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTask14",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTask15",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTask16",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTask17",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTask18",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTask19",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTask20",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTaskCompleted11",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTaskCompleted12",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTaskCompleted13",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTaskCompleted14",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTaskCompleted15",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTaskCompleted16",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTaskCompleted17",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTaskCompleted18",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTaskCompleted19",
        ),
        migrations.RemoveField(
            model_name="tasks",
            name="subTaskCompleted20",
        ),
    ]
