# Generated by Django 4.2.9 on 2024-03-21 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0002_rename_user_usercrop_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="projectName",
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name="tasks",
            name="username",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="PVdb.users",
            ),
        ),
        migrations.AddField(
            model_name="users",
            name="houseStatus",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="taskName",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name="tasks",
            unique_together={("taskName", "username")},
        ),
    ]
