# Generated by Django 5.0.3 on 2024-04-16 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0002_alter_tasks_id_alter_userdecorations_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdecorations',
            name='x',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='userdecorations',
            name='y',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='userfarm',
            name='x',
            field=models.PositiveIntegerField(default=70, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='userfarm',
            name='y',
            field=models.PositiveIntegerField(default=570, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='userfurniture',
            name='x',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='userfurniture',
            name='y',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='userplots',
            name='x',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='userplots',
            name='y',
            field=models.PositiveIntegerField(default=2000, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
