# Generated by Django 4.2.11 on 2024-04-10 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0002_remove_tasks_taskstatus_tasks_pomodorroscompleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usercrop",
            name="id",
        ),
        migrations.AlterField(
            model_name="usercrop",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="PVdb.users",
            ),
        ),
    ]
