# Generated by Django 4.2.11 on 2024-04-10 17:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0003_remove_usercrop_id_alter_usercrop_username"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="PVdb.users",
                    ),
                ),
                (
                    "pomTimer",
                    models.IntegerField(
                        default=25,
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
                (
                    "shortBreak",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
                (
                    "longBreak",
                    models.IntegerField(
                        default=20,
                        validators=[django.core.validators.MaxValueValidator(120)],
                    ),
                ),
                (
                    "longBreakInterval",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(20)],
                    ),
                ),
                ("autoStartPom", models.BooleanField(default=False)),
                ("autoStartBreak", models.BooleanField(default=False)),
                ("autoHideTime", models.BooleanField(default=False)),
                ("fontStyle", models.CharField(max_length=15)),
                (
                    "fontSize",
                    models.IntegerField(
                        default=5,
                        validators=[django.core.validators.MaxValueValidator(5)],
                    ),
                ),
            ],
        ),
    ]
