# Generated by Django 4.2.9 on 2024-03-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0003_tasks_projectname_tasks_username_users_housestatus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDates",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=False)),
                (
                    "username",
                    models.ForeignKey(
                        default=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="PVdb.users",
                    ),
                ),
            ],
            options={
                "unique_together": {("username", "date")},
            },
        ),
    ]
