# Generated by Django 4.2.11 on 2024-04-11 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0004_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="fontSize",
            field=models.IntegerField(
                default=5, validators=[django.core.validators.MaxValueValidator(15)]
            ),
        ),
    ]
