# Generated by Django 5.0.3 on 2024-04-15 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0004_rename_breaktime_tasks_timertime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='fontSize',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='fontStyle',
            field=models.CharField(default='pixel', max_length=15),
        )
    ]
