# Generated by Django 4.2.11 on 2024-04-12 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0004_alter_tasks_subtask1_alter_tasks_subtask10_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="taskCompleted",
            new_name="completed",
        ),
        migrations.RenameField(
            model_name="tasks",
            old_name="pomodorros",
            new_name="pomodoros",
        ),
        migrations.RenameField(
            model_name="tasks",
            old_name="pomodorrosCompleted",
            new_name="pomodorosCompleted",
        ),
        migrations.RenameField(
            model_name="userdecorations",
            old_name="decoration",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="userfurniture",
            old_name="furniture",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="userplots",
            old_name="cropType",
            new_name="crop",
        ),
        migrations.RenameField(
            model_name="userplots",
            old_name="plotNumber",
            new_name="plotId",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="money",
            new_name="coins",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="houseStatus",
            new_name="farmHouseLevel",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="username",
            new_name="usernameId",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="housex",
            new_name="x",
        ),
        migrations.RenameField(
            model_name="users",
            old_name="housey",
            new_name="y",
        ),
        migrations.AlterUniqueTogether(
            name="userdecorations",
            unique_together={("username", "type")},
        ),
        migrations.AlterUniqueTogether(
            name="userfurniture",
            unique_together={("username", "type")},
        ),
    ]
