# Generated by Django 5.0.3 on 2024-04-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0005_alter_usersettings_fontsize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfarm',
            name='plots',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
