# Generated by Django 5.0.3 on 2024-04-17 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0005_alter_tasks_id_alter_userdecorations_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfarm',
            name='coins',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userfarm',
            name='farmHouseLevel',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='userfarm',
            name='x',
            field=models.PositiveIntegerField(blank=True, default=70, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='userfarm',
            name='y',
            field=models.PositiveIntegerField(blank=True, default=570, validators=[django.core.validators.MaxValueValidator(2000)]),
        ),
    ]
