# Generated by Django 4.2.11 on 2024-04-12 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0006_rename_username_tasks_usernameid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="elapsedTime",
            field=models.FloatField(
                default=0, validators=[django.core.validators.MaxValueValidator(40)]
            ),
        ),
    ]
