# Generated by Django 5.0.3 on 2024-04-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0006_remove_tasks_completiondate_delete_pomodorosession"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdates",
            name="timeSpent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
