# Generated by Django 5.0.3 on 2024-04-15 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0006_userfarm_plots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfarm',
            name='plots',
        ),
    ]
