# Generated by Django 5.0.3 on 2024-04-15 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0007_remove_userfarm_plots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseeds',
            name='usernameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PVdb.userfarm'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='usernameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='PVdb.userfarm'),
        ),
    ]
