# Generated by Django 4.2.11 on 2024-04-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0007_tasks_elapsedtime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="subTask1",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask10",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask2",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask3",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask4",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask5",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask6",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask7",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask8",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTask9",
            field=models.CharField(default=None, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTaskCompleted1",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTaskCompleted10",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTaskCompleted2",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTaskCompleted3",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTaskCompleted4",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTaskCompleted5",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTaskCompleted6",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTaskCompleted7",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTaskCompleted8",
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="subTaskCompleted9",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
