# Generated by Django 5.0.3 on 2024-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0007_userdates_timespent"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="plots",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
