# Generated by Django 5.0.3 on 2024-04-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0008_users_plots"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="cropType",
            field=models.CharField(default=None, max_length=30),
        ),
    ]
