# Generated by Django 5.0.3 on 2024-04-16 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0010_alter_userfarm_farmhouselevel_alter_userfarm_x_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFarm',
            new_name='User',
        ),
    ]
