# Generated by Django 5.0.3 on 2024-04-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PVdb', '0011_rename_userfarm_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserFarm',
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='fontStyle',
            field=models.CharField(default='pixelArt', max_length=15),
        ),
    ]
