# Generated by Django 4.2.9 on 2024-02-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="decorations",
            name="image",
        ),
        migrations.AddField(
            model_name="crops",
            name="bought",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="decorations",
            name="bought",
            field=models.BooleanField(default=False),
        ),
    ]
