# Generated by Django 4.2.9 on 2024-03-11 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0002_rename_user_usercrop_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="dateCompleteed",
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name="tasks",
            name="timeSpent",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="users",
            name="plots",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
