# Generated by Django 4.2.9 on 2024-03-11 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PVdb", "0003_tasks_datecompleteed_tasks_timespent_users_plots"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tasks",
            old_name="dateCompleteed",
            new_name="dateCompleted",
        ),
    ]
