# Generated by Django 5.0.3 on 2024-03-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('worth', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Decorations',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskName', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('taskCompleted', models.BooleanField(default=False)),
                ('taskStatus', models.PositiveIntegerField(default=0)),
                ('plotNumber', models.PositiveIntegerField(default=0)),
                ('pomodorros', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('money', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserDecorations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.CharField(default=None, max_length=12)),
                ('decoration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.decorations')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.users')),
            ],
            options={
                'unique_together': {('username', 'decoration')},
            },
        ),
        migrations.CreateModel(
            name='UserCrop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.crops')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DB.users')),
            ],
            options={
                'unique_together': {('username', 'crop')},
            },
        ),
    ]
