# Generated by Django 4.2.9 on 2024-02-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Database", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Decorations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("price", models.PositiveIntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskName", models.CharField(max_length=30)),
                ("taskCompleted", models.BooleanField(default=False)),
                ("taskStatus", models.IntegerField()),
                ("pomodorros", models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="users",
            name="money",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
